### ISSUE TITLE
unable to purchase portable canoe from store

### ISSUE THREAD

**Issue by yaboibutt3r** [BryceCanyonCounty/bcc-boats#33]
all other boats seem to work but when I try to purchase one of the portable canoes it lets me get to the name process and after I enter the name it freezes all the players movement and you have to quit to gain control of your character. This is what its reading in main console, picture also attached
![Desktop Screenshot 2024 08 15 - 18 41 52 39](https://github.com/user-attachments/assets/ff33d2ba-d3f0-46c8-8ba3-260d5484a50b)

 [    script:vorp_core] SCRIPT ERROR: citizen:/scripting/lua/scheduler.lua:739: SCRIPT ERROR: @bcc-boats/server/server.lua:86: bcc-boats was unable to execute a query!
[    script:vorp_core] Query: INSERT INTO `boats` (identifier, charid, name, model) VALUES (?, ?, ?, ?)
[    script:vorp_core] ["steam:11000014e83380f",1,"1","pirogue2"]
[    script:vorp_core] Field 'fuel' doesn't have a default value
[    script:vorp_core] > ref (@bcc-boats/server/server.lua:86)
[    script:vorp_core] > logError (@oxmysql/dist/build.js:26906)
[    script:vorp_core] > rawQuery (@oxmysql/dist/build.js:27085)
[    script:vorp_core] > runMicrotasks (<anonymous>:0)
[    script:vorp_core] > processTicksAndRejections (node:internal/process/task_queues:96)
[    script:vorp_core] 
[    script:vorp_core] > Trigger (@vorp_core/server/class/callbacks.lua:25)
[    script:vorp_core] > handler (@vorp_core/server/class/callbacks.lua:39)
[    script:vorp_core] > logError (@oxmysql/dist/build.js:26906)
[    script:vorp_core] > rawQuery (@oxmysql/dist/build.js:27085)
[    script:vorp_core] > runMicrotasks (<anonymous>:0)
[    script:vorp_core] > processTicksAndRejections (node:internal/process/task_queues:96)

**Comment by yaboibutt3r** [comment]
apparently its actually every boat you buy, there's a error with the fuel field obviously based on what I sent you I just didn't realize it was for every single boat you try to purchase.. hopefully its a easy fix!

**Comment by JusCampin** [comment]
Just submitted a PR to fix this. To fix it right now you can just change the default value for fuel and condition to null.

**Comment by yaboibutt3r** [comment]
thanks it worked!
